GitHub module style
claranet/puppet-consul_template pull request #111
Opened 2017-11-29 15:09 UTC by sts

Adopt module structure to the [Github internal fork](https://github.com/github/puppet-consul_template). Closes #100 

The code was tested on Debian so far and worked, also added a more detailed changelog entry to outline the changes.

2017-11-29 15:18 UTC, craigwatson requested changes
Thanks for all your work, looks great!

There's one minor metadata change here which should allow tests to pass :)

2017-11-29 15:18 UTC, craigwatson commented on metadata.json
> +    { "name": "solarkennedy/puppet-consul", "version_requirement": ">= 2.1.1" }
This should be `KyleAnderson/consul`

2017-11-29 18:39 UTC, wyardley commented on spec/classes/consul_template_spec.rb
> +            #'kernel'           => 'Linux',
Probably should remove this vs. commenting it out?

2017-11-29 18:41 UTC, wyardley commented on spec/defines/watch_spec.rb
> +            :operatingsystem => os,
Shouldn't `:kernel` and `:operatingsystem` already  be available from rspec-puppet-facts?

2017-11-29 18:43 UTC, wyardley commented
@sts Thanks for doing this, much appreciated, as we rely on this functionality as well (though rebasing #100 is going to be a lot of fun).
👍
Put a couple comments inline, though  I don't think they're super important.

2017-11-29 18:45 UTC, wyardley commented on manifests/watch.pp
> +  if $template == undef {
Maybe `unless $template` accomplishes the same thing in a more idiomatic way?

2017-11-30 11:27 UTC, merged

2017-12-02 06:03 UTC, wyardley commented
@ross FYI, this attempts to bring the changes from your fork back upstream.
Also proposing some major changes in #108 (not yet merged as of time of writing). Would love if you have any feedback.